// resources/js/Pages/Home.vue
<template>
    <section class="home__header-section" id="hero-section">
        <h1 class="home__header-name">
            Igor Józefowicz
        </h1>

        <Link href="/blog" class="home__header-blog-link">
            Blog
        </Link>
  
      <!-- If you want to display a header image, adjust the path accordingly -->
      <!-- <div class="home__header-image-wrapper">
           <img src="/storage/favicon.png" alt="Igor Józefowicz" class="home__header-image">
           </div> -->
  
      <h2 class="home__subheader-role">
        Software Engineer
      </h2>
  
      <div class="home__links-wrapper">
        <div class="home__link-wrapper">
          <a
            href="https://github.com/igorjoz"
            class="home__image-wrapper-link"
            target="_blank"
            rel="noopener noreferrer"
            title="&commat;igorjoz">
            <img src="/storage/app/public/icons/github.png" alt="Github" class="home__link-image">
          </a>
          <a
            href="https://github.com/igorjoz"
            class="home__contact-link"
            target="_blank"
            rel="noopener noreferrer"
            title="&commat;igorjoz">
            Github
          </a>
        </div>
  
        <div class="home__link-wrapper">
          <a
            href="https://www.linkedin.com/in/igor-jozefowicz/"
            class="home__image-wrapper-link"
            target="_blank"
            rel="noopener noreferrer"
            title="/in/igor-jozefowicz/">
            <img src="/storage/app/public/icons/linkedin.png" alt="LinkedIn" class="home__link-image">
          </a>
          <a
            href="https://www.linkedin.com/in/igor-jozefowicz/"
            class="home__contact-link"
            target="_blank"
            rel="noopener noreferrer"
            title="/in/igor-jozefowicz/">
            LinkedIn
          </a>
        </div>
  
        <div class="home__link-wrapper">
          <a
            href="mailto:igor@jozefowicz.pl"
            class="home__image-wrapper-link"
            rel="noopener noreferrer"
            title="igor@jozefowicz.pl">
            <img src="/storage/app/public/icons/email.png" alt="Email" class="home__link-image">
          </a>
          <a
            href="mailto:igor@jozefowicz.pl"
            class="home__contact-link"
            rel="noopener noreferrer"
            title="igor@jozefowicz.pl">
            Email
          </a>
        </div>
      </div>
  
      <div class="scroll-arrow">
        <a href="#bio-section">
          <i class="fa fa-chevron-down" aria-hidden="true"></i>
        </a>
      </div>
    </section>
  
    <section class="home__bio-section" id="bio-section">
      <div class="home__bio-text-wrapper">
        <h2 class="home__bio-header">
          About me
        </h2>
        <p class="home__bio-text">
          Hello there! I'm Igor Józefowicz, also known as
          <a href="https://github.com/igorjoz" target="_blank" rel="noopener noreferrer" class="home__link">
            &commat;igorjoz</a>.
          Since 2018, I've&nbsp;been immersed in web development, focusing on PHP & Laravel to&nbsp;create impactful digital solutions.
          I&nbsp;complement my technical endeavors with academic studies in Computer Science at Gdańsk University of Technology.
        </p>
        <p class="home__bio-text">
          As a&nbsp;passionate educator, I&nbsp;teach programming at Giganci Programowania, covering topics from Hacking & Cybersecurity to Python and C++.
          When not teaching, I&nbsp;enjoy challenging myself with Competitive Programming contests and deepening my&nbsp;understanding of Computer Architecture & Assembly, alongside Database Design.
        </p>
        <p class="home__bio-text">
          I'm excited to connect with fellow tech enthusiasts and professionals.
          Explore my website to learn more about my work or reach out on
          <a href="https://www.linkedin.com/in/igor-jozefowicz/" target="_blank" rel="noopener noreferrer" class="home__link">
            LinkedIn</a>.
          For collaborations or inquiries, don't hesitate to send me an email:
          <a href="mailto:igor@jozefowicz.pl" target="_blank" rel="noopener noreferrer" class="home__link">
            igor@jozefowicz.pl</a>.
        </p>
      </div>
    </section>
  
    <section class="home__projects-section" id="projects-section">
      <div class="home__projects-text-wrapper">
        <h2 class="home__projects-header">
          Projects
        </h2>
        <p class="home__projects-text">
          🏆 My major achievement in web development is the
          <a href="https://www.e-kominki.com/" target="_blank" rel="noopener noreferrer" class="home__link">
            Vento website & online shop</a>, created in&nbsp;2020-2021 for a&nbsp;Polish company specializing in heating and ventilation.
        </p>
        <p class="home__projects-text">
          ⭐ I've&nbsp;also developed several Laravel applications, such as the
          <a href="https://github.com/igorjoz/employees_directory" target="_blank" rel="noopener noreferrer" class="home__link">
            Employees&nbsp;Directory</a>, a&nbsp;database management software for employees and departments,
          and the
          <a href="https://github.com/igorjoz/anon-surv" target="_blank" rel="noopener noreferrer" class="home__link">
            Anonymous&nbsp;Surveys</a> app, allowing users to create and analyze anonymous surveys.
        </p>
        <p class="home__projects-text">
          🎯 Some other notable projects include the
          <a href="https://github.com/igorjoz/spy-hunter-game" target="_blank" rel="noopener noreferrer" class="home__link">
            Spy&nbsp;Hunter&nbsp;Game</a>, an&nbsp;Atari 2600-styled game,
          the&nbsp;Python-based
          <a href="https://github.com/igorjoz/game-of-life-python" target="_blank" rel="noopener noreferrer" class="home__link">
            Game&nbsp;of&nbsp;Life</a>, and the
          <a href="https://github.com/igorjoz/css-processor" target="_blank" rel="noopener noreferrer" class="home__link">
            CSS&nbsp;Processor</a> for Algorithms & Data Structures course.
        </p>
      </div>
    </section>
  
    <section class="home__project-cards-section">
      <div class="project-card">
        <div class="project-card__image-wrapper">
          <img src="/storage/app/public/projects/vento-logo.svg" alt="Vento Website" class="project-card__image project-card__image--short project-card__image--vento">
        </div>
        <div class="project-card__content">
          <h3 class="project-card__title">Vento Kominki Website&nbsp;& Online Shop</h3>
          <p class="project-card__description">
            A comprehensive Laravel web application for Vento, focusing on heating and ventilation solutions.
            Developed in 2020-2021.
          </p>
          <a href="https://www.e-kominki.com/" target="_blank" rel="noopener noreferrer" class="project-card__link">
            Visit website</a>
        </div>
      </div>
  
      <div class="project-card">
        <div class="project-card__image-wrapper">
          <img src="/storage/app/public/projects/employees_directory.webp" alt="Employees Directory" class="project-card__image">
        </div>
        <div class="project-card__content">
          <h3 class="project-card__title">Employees Directory</h3>
          <p class="project-card__description">A Laravel app for managing employees and departments.</p>
          <a href="https://github.com/igorjoz/employees_directory" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View repository</a>
        </div>
      </div>
  
      <div class="project-card">
        <div class="project-card__image-wrapper">
          <img src="/storage/app/public/projects/anonymous-surveys.webp" alt="Anonymous Surveys" class="project-card__image">
        </div>
        <div class="project-card__content">
          <h3 class="project-card__title">Anonymous Surveys</h3>
          <p class="project-card__description">
            A Laravel app that allows users to create anonymous surveys.
          </p>
          <a href="https://github.com/igorjoz/anon-surv" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View repository</a>
        </div>
      </div>
  
      <div class="project-card">
        <div class="project-card__image-wrapper">
          <img src="/storage/app/public/projects/driving-course-for-ai.webp" alt="Driving Course for AI" class="project-card__image">
        </div>
        <div class="project-card__content">
          <h3 class="project-card__title">Driving Course for AI</h3>
          <p class="project-card__description">Machine learning project made with Unity. And a bit of love!</p>
          <a href="https://docs.google.com/document/d/1jKZnomEy_Bo613_xQswbK1qzhcIcbXEKB5TfghTAJYg/edit?usp=sharing" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View documentation</a>
          <a href="https://github.com/igorjoz/anon-surv" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View repository</a>
        </div>
      </div>
  
      <div class="project-card">
        <div class="project-card__image-wrapper">
          <img src="/storage/app/public/projects/vulnerability-vault.webp" alt="Vulnerability Vault" class="project-card__image">
        </div>
        <div class="project-card__content">
          <h3 class="project-card__title">Vulnerability Vault</h3>
          <p class="project-card__description">
            Do you want to learn hacking? Check out my cybersec project.
          </p>
          <a href="https://igorjozefowicz.com/" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View website</a>
          <a href="https://github.com/igorjoz/vulnerability-vault" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View repository</a>
        </div>
      </div>
  
      <div class="project-card">
        <div class="project-card__image-wrapper">
          <img src="/storage/app/public/projects/game-of-life.webp" alt="Game of Life" class="project-card__image">
        </div>
        <div class="project-card__content">
          <h3 class="project-card__title">Game of Life</h3>
          <p class="project-card__description">
            A turn-based game written in Python, pygame and Java, Spring
          </p>
          <a href="https://github.com/igorjoz/game-of-life-python" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View Python repository</a>
          <a href="https://github.com/igorjoz/game-of-life-java" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View Java repository</a>
        </div>
      </div>
  
      <div class="project-card">
        <div class="project-card__image-wrapper">
          <img src="/storage/app/public/projects/spy-hunter-crop.png" alt="Spy Hunter Game" class="project-card__image">
        </div>
        <div class="project-card__content">
          <h3 class="project-card__title">Spy Hunter Game</h3>
          <p class="project-card__description">
            An Atari 2600-styled game created with C++ & SDL library.
          </p>
          <a href="https://github.com/igorjoz/spy-hunter-game" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View Repository</a>
        </div>
      </div>
  
      <div class="project-card">
        <div class="project-card__image-wrapper">
          <img src="/storage/app/public/projects/finance-and-investing.webp" alt="Finance and Investing" class="project-card__image">
        </div>
        <div class="project-card__content">
          <h3 class="project-card__title">Finance and Investing</h3>
          <p class="project-card__description">
            A PHP application created without backend framework.
          </p>
          <a href="https://github.com/igorjoz/finance-and-investing/tree/main/src" target="_blank" rel="noopener noreferrer" class="project-card__link">
            View repository</a>
        </div>
      </div>
  
        <div class="project-card">
            <div class="project-card__image-wrapper">
                <img src="/storage/app/public/projects/matura.webp" alt="Matura Exam Solutions" class="project-card__image">
            </div>

            <div class="project-card__content">
                <h3 class="project-card__title">Matura Exam Solutions</h3>

                <p class="project-card__description">
                    Solutions for 2014-2022 Polish Matura exam sheets.
                </p>

                <a href="https://github.com/igorjoz/matura" target="_blank" rel="noopener noreferrer" class="project-card__link">
                    View repository
                </a>
            </div>
        </div>
    </section>
</template>
    
<script>
    import { Link } from '@inertiajs/inertia-vue3';

    import Navigation from '../components/Navigation.vue';

    export default {
      components: { Link, Navigation },
    };
</script>

// resources/js/Pages/Home/Index.jsx
import { Head } from '@inertiajs/react';
import Layout from '@/Layouts/Layout';
import SocialLink from '@/Components/SocialLink';
import ScrollArrow from '@/Components/ScrollArrow';
import ProjectCard from '@/Components/ProjectCard';
import { storageUrl } from '@/utils/assets';

export default function Index() {
    const projects = [
        {
            imgSrc: storageUrl('public/projects/vento-logo.svg'),
            imgAlt: 'Vento Website',
            title: 'Vento Kominki Website & Online Shop',
            description: 'A comprehensive Laravel web application for Vento, focusing on heating and ventilation solutions. Developed in 2020-2021.',
            links: [
                { text: 'Visit website', url: 'https://www.e-kominki.com/' }
            ],
            isShortImage: true,
            extraClass: 'project-card__image--vento'
        },
        {
            imgSrc: storageUrl('public/projects/employees_directory.webp'),
            imgAlt: 'Employees Directory',
            title: 'Employees Directory',
            description: 'A Laravel app for managing employees and departments.',
            links: [
                { text: 'View repository', url: 'https://github.com/igorjoz/employees_directory' }
            ]
        },
        {
            imgSrc: storageUrl('public/projects/anonymous-surveys.webp'),
            imgAlt: 'Anonymous Surveys',
            title: 'Anonymous Surveys',
            description: 'A Laravel app that allows users to create anonymous surveys.',
            links: [
                { text: 'View repository', url: 'https://github.com/igorjoz/anon-surv' }
            ]
        },
        {
            imgSrc: storageUrl('public/projects/driving-course-for-ai.webp'),
            imgAlt: 'Driving Course for AI',
            title: 'Driving Course for AI',
            description: 'Machine learning project made with Unity. And a bit of love!',
            links: [
                { text: 'View documentation', url: 'https://docs.google.com/document/d/1jKZnomEy_Bo613_xQswbK1qzhcIcbXEKB5TfghTAJYg/edit?usp=sharing' },
                { text: 'View repository', url: 'https://github.com/igorjoz/anon-surv' }
            ]
        },
        {
            imgSrc: storageUrl('public/projects/vulnerability-vault.webp'),
            imgAlt: 'Vulnerability Vault',
            title: 'Vulnerability Vault',
            description: 'Do you want to learn hacking? Check out my cybersec project.',
            links: [
                { text: 'View website', url: 'https://igorjozefowicz.com/' },
                { text: 'View repository', url: 'https://github.com/igorjoz/vulnerability-vault' }
            ]
        },
        {
            imgSrc: storageUrl('public/projects/game-of-life.webp'),
            imgAlt: 'Game of Life',
            title: 'Game of Life',
            description: 'A turn-based game written in Python, pygame and Java, Spring',
            links: [
                { text: 'View Python repository', url: 'https://github.com/igorjoz/game-of-life-python' },
                { text: 'View Java repository', url: 'https://github.com/igorjoz/game-of-life-java' }
            ]
        },
        {
            imgSrc: storageUrl('public/projects/spy-hunter-crop.png'),
            imgAlt: 'Spy Hunter Game',
            title: 'Spy Hunter Game',
            description: 'An Atari 2600-styled game created with C++ & SDL library.',
            links: [
                { text: 'View Repository', url: 'https://github.com/igorjoz/spy-hunter-game' }
            ]
        },
        {
            imgSrc: storageUrl('public/projects/finance-and-investing.webp'),
            imgAlt: 'Finance and Investing',
            title: 'Finance and Investing',
            description: 'A PHP application created without backend framework.',
            links: [
                { text: 'View repository', url: 'https://github.com/igorjoz/finance-and-investing/tree/main/src' }
            ]
        },
        {
            imgSrc: storageUrl('public/projects/matura.webp'),
            imgAlt: 'Matura Exam Solutions',
            title: 'Matura Exam Solutions',
            description: 'Solutions for 2014-2022 Polish Matura exam sheets.',
            links: [
                { text: 'View repository', url: 'https://github.com/igorjoz/matura' }
            ]
        }
    ];

    return (
        <Layout>
            <Head title="Home" />

            {/* Hero Section */}
            <section className="min-h-screen flex flex-col items-center justify-center text-white px-4" id="hero-section">
                <h1 className="text-6xl xs:text-7xl sm:text-8xl md:text-9xl font-bold mb-36 text-center" style={{ textShadow: '4px 4px 0px rgba(255, 192, 203, 0.8)' }}>
                    Igor Józefowicz
                </h1>

                <h2 className="text-5xl xs:text-6xl sm:text-7xl md:text-8xl text-white mb-36 text-center font-bold">
                    Software Engineer
                </h2>

                <div className="flex flex-col sm:flex-row flex-wrap gap-8 sm:gap-12 justify-center mb-16">
                    <SocialLink
                        href="https://github.com/igorjoz"
                        imgSrc={storageUrl('public/icons/github.png')}
                        imgAlt="Github"
                        text="Github"
                        title="@igorjoz"
                    />
                    <SocialLink
                        href="https://www.linkedin.com/in/igor-jozefowicz/"
                        imgSrc={storageUrl('public/icons/linkedin.png')}
                        imgAlt="LinkedIn"
                        text="LinkedIn"
                        title="/in/igor-jozefowicz/"
                    />
                    <SocialLink
                        href="mailto:igor@jozefowicz.pl"
                        imgSrc={storageUrl('public/icons/email.png')}
                        imgAlt="Email"
                        text="Email"
                        title="igor@jozefowicz.pl"
                    />
                </div>

                <ScrollArrow targetId="bio-section" />
            </section>

            {/* Bio Section */}
            <section className="min-h-[90vh] flex items-center justify-center py-20 px-4" id="bio-section">
                <div className="max-w-7xl mx-auto w-full">
                    <h2 className="text-5xl xs:text-6xl sm:text-7xl md:text-8xl font-bold mb-20 text-white text-center underline decoration-pink-300 decoration-2 underline-offset-8">
                        About me
                    </h2>

                    <div className="space-y-8 text-white text-xl sm:text-2xl md:text-3xl leading-relaxed">
                        <p>
                            Hello there! I'm Igor Józefowicz, also known as <a href="https://github.com/igorjoz" target="_blank" rel="noopener noreferrer" className="text-pink-500 hover:text-pink-600 underline decoration-wavy transition-all hover:scale-105 inline-block">@igorjoz</a>. Since 2018, I've been immersed in web development, focusing on PHP & Laravel to create impactful digital solutions. I complement my technical endeavors with academic studies in Computer Science at Gdańsk University of Technology.
                        </p>

                        <p>
                            As a passionate educator, I teach programming at Giganci Programowania, covering topics from Hacking & Cybersecurity to Python and C++. When not teaching, I enjoy challenging myself with Competitive Programming contests and deepening my understanding of Computer Architecture & Assembly, alongside Database Design.
                        </p>

                        <p>
                            I'm excited to connect with fellow tech enthusiasts and professionals. Explore my website to learn more about my work or reach out on <a href="https://www.linkedin.com/in/igor-jozefowicz/" target="_blank" rel="noopener noreferrer" className="text-pink-500 hover:text-pink-600 underline decoration-wavy transition-all hover:scale-105 inline-block">LinkedIn</a>. For collaborations or inquiries, don't hesitate to send me an email: <a href="mailto:igor@jozefowicz.pl" className="text-pink-500 hover:text-pink-600 underline decoration-wavy transition-all hover:scale-105 inline-block">igor@jozefowicz.pl</a>.
                        </p>
                    </div>
                </div>
            </section>

            {/* Projects Intro Section */}
            <section className="min-h-[90vh] flex items-center justify-center py-20 px-4" id="projects-section">
                <div className="max-w-7xl mx-auto w-full">
                    <h2 className="text-5xl xs:text-6xl sm:text-7xl md:text-8xl font-bold mb-20 text-white text-center underline decoration-white decoration-2 underline-offset-8">
                        Projects
                    </h2>

                    <div className="space-y-8 text-white text-xl sm:text-2xl md:text-3xl leading-relaxed">
                        <p>
                            🏆 My major achievement in web development is the <a href="https://www.e-kominki.com/" target="_blank" rel="noopener noreferrer" className="text-pink-300 hover:text-pink-200 underline decoration-wavy transition-all inline-block font-semibold">Vento website & online shop</a>, created in 2020-2021 for a Polish company specializing in heating and ventilation.
                        </p>

                        <p>
                            ⭐ I've also developed several Laravel applications, such as the <a href="https://github.com/igorjoz/employees_directory" target="_blank" rel="noopener noreferrer" className="text-pink-300 hover:text-pink-200 underline decoration-wavy transition-all inline-block font-semibold">Employees Directory</a>, a database management software for employees and departments, and the <a href="https://github.com/igorjoz/anon-surv" target="_blank" rel="noopener noreferrer" className="text-pink-300 hover:text-pink-200 underline decoration-wavy transition-all inline-block font-semibold">Anonymous Surveys</a> app, allowing users to create and analyze anonymous surveys.
                        </p>

                        <p>
                            🎯 Some other notable projects include the <a href="https://github.com/igorjoz/spy-hunter-game" target="_blank" rel="noopener noreferrer" className="text-pink-300 hover:text-pink-200 underline decoration-wavy transition-all inline-block font-semibold">Spy Hunter Game</a>, an Atari 2600-styled game, the Python-based <a href="https://github.com/igorjoz/game-of-life-python" target="_blank" rel="noopener noreferrer" className="text-pink-300 hover:text-pink-200 underline decoration-wavy transition-all inline-block font-semibold">Game of Life</a>, and the <a href="https://github.com/igorjoz/css-processor" target="_blank" rel="noopener noreferrer" className="text-pink-300 hover:text-pink-200 underline decoration-wavy transition-all inline-block font-semibold">CSS Processor</a> for Algorithms & Data Structures course.
                        </p>
                    </div>
                </div>
            </section>

            {/* Project Cards Section */}
            <section className="py-20 px-4">
                <div className="max-w-7xl 2xl:max-w-[1500px] mx-auto">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 2xl:gap-10">
                        {projects.map((project, index) => (
                            <ProjectCard
                                key={index}
                                imgSrc={project.imgSrc}
                                imgAlt={project.imgAlt}
                                title={project.title}
                                description={project.description}
                                links={project.links}
                                isShortImage={project.isShortImage}
                                extraClass={project.extraClass}
                            />
                        ))}
                    </div>
                </div>
            </section>
        </Layout>
    );
}
